const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],pad=n=>String(n).padStart(2,'0'),dateKey=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const today=dateKey(new Date()),nowMonth=today.slice(0,7);
const initial={members:[['林怡君','ICU',true],['林武甫','ICU'],['林曉楓','ICU'],['王彩蘋','ICU'],['葉靜婷','ICU'],['郭珮銜','病房'],['張慧玲','病房'],['李慧娟','病房']].map((x,i)=>({id:'m'+i,name:x[0],group:x[1],admin:!!x[2],pin:'00000'})),limits:{ICU:1,病房:3},phaseLimits:{1:2,2:31},schedule:{bookingMonth:nowMonth,p1End:today,p2Start:today,p2End:today,p3Start:today,p3End:today,longStart:nowMonth,longEnd:nowMonth},phase:1,bookings:{}};
const restored=JSON.parse(localStorage.getItem('npLeavePlanner')||localStorage.getItem('leavePlanner')||'null');
let state=restored||initial,view=new Date(`${state.schedule?.bookingMonth||nowMonth}-01T12:00:00`),selected='';
if(restored?.schedule?.phase1Deadline)state.schedule={...restored.schedule,p1End:restored.schedule.phase1Deadline,p2Start:restored.schedule.phase2Start,p2End:restored.schedule.phase2End,p3Start:restored.schedule.phase3Start,p3End:restored.schedule.phase3End,longStart:restored.schedule.longMonthStart,longEnd:restored.schedule.longMonthEnd};
state.schedule={...initial.schedule,...state.schedule};state.limits={...initial.limits,...state.limits};state.phaseLimits={...initial.phaseLimits,...state.phaseLimits};
const holidays={'2026-01-01':'元旦','2026-02-16':'除夕','2026-02-17':'春節','2026-02-18':'春節','2026-02-19':'春節','2026-02-20':'春節','2026-02-27':'和平紀念日補假','2026-04-03':'兒童節補假','2026-04-06':'清明節補假','2026-05-01':'勞動節','2026-06-19':'端午節','2026-09-25':'中秋節','2026-09-28':'教師節','2026-10-09':'國慶日補假','2026-10-26':'光復節補假','2026-12-25':'行憲紀念日'};
function save(){localStorage.setItem('npLeavePlanner',JSON.stringify(state))}function me(){return state.members.find(m=>m.id===sessionStorage.getItem('npAuth'))}function items(k){return state.bookings[k]||[]}function member(id){return state.members.find(m=>m.id===id)}function holiday(d){return d.getDay()===0||d.getDay()===6||holidays[dateKey(d)]}
function phaseOpen(p){if(p===1)return today<=state.schedule.p1End;if(p===2)return today>=state.schedule.p2Start&&today<=state.schedule.p2End;return today>=state.schedule.p3Start&&today<=state.schedule.p3End}
function nearHoliday(d){if(holiday(d))return false;for(let n=-4;n<=4;n++){if(!n)continue;const h=new Date(d);h.setDate(h.getDate()+n);if(!holiday(h))continue;let x=new Date(d),step=n>0?1:-1;for(let i=0;i<4;i++){x.setDate(x.getDate()+step);if(dateKey(x)===dateKey(h))return true;if(!holiday(x))break}}return false}
function eligible(d){const k=dateKey(d);if(state.phase===3){const m=k.slice(0,7);return m>=state.schedule.longStart&&m<=state.schedule.longEnd}return k.startsWith(state.schedule.bookingMonth)&&!holiday(d)&&(state.phase===2||nearHoliday(d))}
function relevant(b){return state.phase===3?b.phase===3:b.phase!==3}function groupCount(k,g){return items(k).filter(b=>b.phase!==3&&member(b.memberId)?.group===g).length}function longCount(k){return items(k).filter(b=>b.phase===3).length}
function phaseCount(id,p){return Object.values(state.bookings).flat().filter(b=>b.memberId===id&&b.phase===p).length}function blocks(id){return new Set(Object.values(state.bookings).flat().filter(b=>b.memberId===id&&b.phase===3).map(b=>b.blockId)).size}
function toast(s){const t=$('#toast');t.textContent=s;t.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove('show'),2200)}
function syncUser(){const m=me();$('#who').textContent=m?`${m.name}｜${m.group}${m.admin?'｜管理員':''}`:'尚未登入';$('#adminBtn').hidden=!m?.admin}
function syncPhases(){const admin=me()?.admin,open=[1,2,3].filter(phaseOpen);$$('[data-phase]').forEach(b=>b.hidden=!admin&&!open.includes(+b.dataset.phase));if(!admin&&open.length&&!open.includes(state.phase))state.phase=open[0]}
function render(){syncPhases();syncUser();const y=view.getFullYear(),mo=view.getMonth(),p=state.phase;$('#monthTitle').textContent=`${y} 年 ${mo+1} 月`;$('#phaseTitle').textContent=p===1?'假日前後工作日預約':p===2?'一般工作日預約':'長假預約';$('#phaseHint').textContent=p===3?`可預約月份 ${state.schedule.longStart} 至 ${state.schedule.longEnd}；每次連續 7 天（含假日），每日共用名額 1 人。${phaseOpen(3)?'目前開放':'目前未開放'}`:`預約月份 ${state.schedule.bookingMonth}；每人最多 ${state.phaseLimits[p]} 天。${phaseOpen(p)?'目前開放':'目前未開放'}`;$$('[data-phase]').forEach(b=>b.classList.toggle('active',+b.dataset.phase===p));const first=new Date(y,mo,1),start=new Date(y,mo,1-first.getDay());let html='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const k=dateKey(d),out=d.getMonth()!==mo,ok=eligible(d),mine=items(k).some(b=>b.memberId===me()?.id&&relevant(b));let badges='';if(p===3){if(ok&&phaseOpen(3)){const used=longCount(k),remain=Math.max(0,1-used);badges+=`<span class="count ${used>1?'over':used===1?'full':''}">長假剩餘 ${remain}</span>`}const names=items(k).filter(b=>b.phase===3).map(b=>member(b.memberId)).filter(Boolean).map(m=>[...m.name].slice(-2).join(''));if(names.length)badges+=`<span class="names">${names.join('、')}</span>`}else for(const g of ['ICU','病房']){const n=groupCount(k,g),lim=state.limits[g],names=items(k).filter(b=>b.phase!==3&&member(b.memberId)?.group===g).map(b=>[...member(b.memberId).name].slice(-2).join(''));if(n)badges+=`<span class="count ${n>lim?'over':n===lim?'full':''}">${g} ${n}/${lim}</span><span class="names">${g} ${names.join('、')}</span>`}html+=`<button class="day ${out?'out':''} ${ok?'':'disabled'} ${k===today?'today':''}" data-date="${k}"><span class="num">${d.getDate()}</span>${mine?'<span class="mine">●</span>':''}${holidays[k]?`<span class="holiday">${holidays[k]}</span>`:(holiday(d)?'<span class="holiday">週末</span>':'')}<span class="counts">${badges}</span></button>`}$('#days').innerHTML=html;const prefix=`${y}-${pad(mo+1)}`,monthEntries=Object.entries(state.bookings).filter(([k])=>k.startsWith(prefix));$('#uniqueCount').textContent=new Set(monthEntries.flatMap(([,a])=>a.map(b=>b.memberId))).size;$('#overCount').textContent=monthEntries.filter(([k])=>p===3?longCount(k)>1:['ICU','病房'].some(g=>groupCount(k,g)>state.limits[g])).length}
function longDates(k){const d=new Date(k+'T12:00:00');return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return dateKey(x)})}function removeBlock(id){for(const k of Object.keys(state.bookings)){state.bookings[k]=items(k).filter(b=>b.blockId!==id);if(!state.bookings[k].length)delete state.bookings[k]}}
function addLong(id,bypass=false){const dates=longDates(selected),inside=dates.every(k=>k.slice(0,7)>=state.schedule.longStart&&k.slice(0,7)<=state.schedule.longEnd);if(!bypass&&!inside)return toast('連續 7 天須全部位於可預約月份內');if(dates.some(k=>items(k).some(b=>b.memberId===id)))return toast('這 7 天內已有該成員的預約');const blockId=`L${Date.now()}${id}`;dates.forEach(k=>(state.bookings[k]??=[]).push({memberId:id,phase:3,blockId}));save();toast(dates.some(k=>longCount(k)>1)?'已登記；部分日期超額待協調':'長假預約成功');closeDay()}
function openDay(k){selected=k;const d=new Date(k+'T12:00:00'),long=state.phase===3,list=items(k).filter(relevant);$('#dayTitle').textContent=`${d.getMonth()+1} 月 ${d.getDate()} 日 星期${'日一二三四五六'[d.getDay()]}`;$('#dayPhase').textContent=long?'長假預約':`第${state.phase===1?'一':'二'}階段`;$('#dayNote').textContent=holidays[k]||(!eligible(d)?'此日期未開放':'可預約日期');$('#capacity').innerHTML=long?`<div class="capacity-row"><span>長假剩餘人數</span><b>${Math.max(0,1-longCount(k))}${longCount(k)>1?'（超額）':''}</b></div>`:['ICU','病房'].map(g=>`<div class="capacity-row"><span>${g}</span><b>${groupCount(k,g)} / ${state.limits[g]}</b></div>`).join('');$('#bookingList').innerHTML=list.length?list.map(b=>`<div class="booking-row ${long?(longCount(k)>1?'over':''):(groupCount(k,member(b.memberId)?.group)>state.limits[member(b.memberId)?.group]?'over':'')}"><span>${member(b.memberId)?.name||'已移除成員'}</span><span>${long?'長假':member(b.memberId)?.group}</span>${me()?.admin?`<button data-remove="${b.memberId}" data-phase="${b.phase}" data-block="${b.blockId||''}">移除${b.phase===3?' 7 天':''}</button>`:''}</div>`).join(''):'<p>目前沒有人預約</p>';$('#adminAdjust').hidden=!me()?.admin;$('#adjustMember').innerHTML=state.members.map(m=>`<option value="${m.id}">${m.name}${long?'':`｜${m.group}`}</option>`).join('');$('#adminAdd').textContent=long?'加入連續 7 天長假':'加入預約';const mine=list.find(b=>b.memberId===me()?.id),btn=$('#reserveBtn');btn.hidden=!me()?.admin&&(!eligible(d)||!phaseOpen(state.phase));btn.textContent=mine?(long?'取消整段 7 天長假':'取消我的預約'):(long?'從這天開始預約 7 天':'預約這一天');$('#dayDlg').showModal()}
function closeDay(){ $('#dayDlg').close();render() }
function toggle(){const m=me();if(!m)return showLogin();if(state.phase===3){const old=items(selected).find(b=>b.memberId===m.id&&b.phase===3);if(old){removeBlock(old.blockId);save();toast('已取消整段長假');closeDay()}else addLong(m.id);return}const arr=items(selected),i=arr.findIndex(b=>b.memberId===m.id&&b.phase!==3);if(i>=0){arr.splice(i,1);if(!arr.length)delete state.bookings[selected];toast('已取消預約')}else{if(phaseCount(m.id,state.phase)>=state.phaseLimits[state.phase])return toast(`本階段最多 ${state.phaseLimits[state.phase]} 天`);(state.bookings[selected]??=[]).push({memberId:m.id,phase:state.phase});toast(groupCount(selected,m.group)>state.limits[m.group]?'已登記；此日超額待協調':'預約成功')}save();closeDay()}
function showLogin(){sessionStorage.removeItem('npAuth');$('#loginMember').innerHTML=state.members.map(m=>`<option value="${m.id}">${m.name}｜${m.group}</option>`).join('');$('#loginPin').value='';$('#loginError').textContent='';$('#loginDlg').showModal();syncUser()}
function renderAdmin(){const s=state.schedule;for(const [id,key] of [['bookingMonth','bookingMonth'],['p1End','p1End'],['p2Start','p2Start'],['p2End','p2End'],['p3Start','p3Start'],['p3End','p3End'],['longStart','longStart'],['longEnd','longEnd']])$('#'+id).value=s[key];$('#p1Max').value=state.phaseLimits[1];$('#p2Max').value=state.phaseLimits[2];$('#icuMax').value=state.limits.ICU;$('#wardMax').value=state.limits.病房;$('#memberRows').innerHTML=state.members.map(m=>`<div class="member-row" data-id="${m.id}"><input value="${m.name}"><select><option ${m.group==='ICU'?'selected':''}>ICU</option><option ${m.group==='病房'?'selected':''}>病房</option></select><button class="reset" type="button">重設 PIN</button><button class="admin-choice ${m.admin?'active':''}" type="button">${m.admin?'目前管理員':'設為管理員'}</button><button class="remove" type="button">移除</button></div>`).join('');$('#adminDlg').showModal()}
function saveAdmin(){const chosen=$('.admin-choice.active')?.closest('.member-row')?.dataset.id;if(!chosen)return toast('必須指定一位管理員');state.schedule={bookingMonth:$('#bookingMonth').value,p1End:$('#p1End').value,p2Start:$('#p2Start').value,p2End:$('#p2End').value,p3Start:$('#p3Start').value,p3End:$('#p3End').value,longStart:$('#longStart').value,longEnd:$('#longEnd').value};if(Object.values(state.schedule).some(v=>!v))return toast('請完整填寫日期');state.phaseLimits={1:Math.max(1,+$('#p1Max').value),2:Math.max(1,+$('#p2Max').value)};state.limits={ICU:Math.max(1,+$('#icuMax').value),病房:Math.max(1,+$('#wardMax').value)};$$('.member-row').forEach(r=>{const m=member(r.dataset.id);if(m){m.name=r.querySelector('input').value.trim()||m.name;m.group=r.querySelector('select').value;m.admin=m.id===chosen}});view=new Date(`${state.schedule.bookingMonth}-01T12:00:00`);save();$('#adminDlg').close();render();toast('設定已儲存')}
function exportExcel(){if(!me()?.admin)return toast('僅管理員可匯出');const month=state.schedule.bookingMonth,[y,mo]=month.split('-').map(Number),rows=[['日期','星期','假日','ICU 預約','ICU 人數','病房預約','病房人數','長假預約','長假人數']];for(let d=1;d<=new Date(y,mo,0).getDate();d++){const dt=new Date(y,mo-1,d),k=dateKey(dt),names=g=>items(k).filter(b=>b.phase!==3&&member(b.memberId)?.group===g).map(b=>member(b.memberId).name).join('、'),long=items(k).filter(b=>b.phase===3).map(b=>member(b.memberId)?.name).filter(Boolean).join('、');rows.push([k,'星期'+'日一二三四五六'[dt.getDay()],holidays[k]||(holiday(dt)?'週末':''),names('ICU'),groupCount(k,'ICU'),names('病房'),groupCount(k,'病房'),long,longCount(k)])}const esc=v=>`"${String(v??'').replaceAll('"','""')}"`,csv='\ufeff'+rows.map(r=>r.map(esc).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=`排假班表_${month}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('已匯出 Excel 相容檔')}
$('#loginForm').onsubmit=e=>{e.preventDefault();const m=member($('#loginMember').value);if(!m||m.pin!==$('#loginPin').value)return $('#loginError').textContent='姓名或 PIN 不正確';sessionStorage.setItem('npAuth',m.id);$('#loginDlg').close();render();toast(`${m.name}，登入成功`)};$('#logoutBtn').onclick=showLogin;$('#pinBtn').onclick=()=>$('#pinDlg').showModal();$('#pinForm').onsubmit=e=>{e.preventDefault();const m=me(),n=$('#newPin').value;if($('#oldPin').value!==m.pin)return $('#pinError').textContent='目前 PIN 不正確';if(!/^\d{5}$/.test(n))return $('#pinError').textContent='新 PIN 必須為 5 位數字';if(n!==$('#confirmPin').value)return $('#pinError').textContent='兩次輸入不一致';m.pin=n;save();$('#pinDlg').close();toast('PIN 已更新')};
$('#days').onclick=e=>{const b=e.target.closest('[data-date]');if(b)openDay(b.dataset.date)};$('#reserveBtn').onclick=toggle;$('#adminAdd').onclick=()=>state.phase===3?addLong($('#adjustMember').value,true):(()=>{const id=$('#adjustMember').value;if(items(selected).some(b=>b.memberId===id&&b.phase!==3))return toast('此成員已預約');(state.bookings[selected]??=[]).push({memberId:id,phase:state.phase});save();closeDay()})();$('#bookingList').onclick=e=>{const b=e.target.closest('[data-remove]');if(!b)return;if(+b.dataset.phase===3)removeBlock(b.dataset.block);else{state.bookings[selected]=items(selected).filter(x=>!(x.memberId===b.dataset.remove&&x.phase!==3));if(!state.bookings[selected].length)delete state.bookings[selected]}save();closeDay()};
$$('[data-phase]').forEach(b=>b.onclick=()=>{state.phase=+b.dataset.phase;save();render()});$('#prev').onclick=()=>{view.setMonth(view.getMonth()-1);render()};$('#next').onclick=()=>{view.setMonth(view.getMonth()+1);render()};$('#printBtn').onclick=()=>print();$('#excelBtn').onclick=exportExcel;$('#adminBtn').onclick=renderAdmin;$('#saveAdmin').onclick=saveAdmin;$('#addMember').onclick=()=>{const n=$('#newName').value.trim();if(!n)return;state.members.push({id:'m'+Date.now(),name:n,group:$('#newGroup').value,pin:'00000',admin:false});$('#newName').value='';renderAdmin()};$('#memberRows').onclick=e=>{const r=e.target.closest('.member-row');if(!r)return;if(e.target.classList.contains('admin-choice')){$$('.admin-choice').forEach(b=>{b.classList.remove('active');b.textContent='設為管理員'});e.target.classList.add('active');e.target.textContent='目前管理員'}if(e.target.classList.contains('reset')){member(r.dataset.id).pin='00000';save();toast('PIN 已重設為 00000')}if(e.target.classList.contains('remove')){if(member(r.dataset.id)?.admin)return toast('不可移除管理員');state.members=state.members.filter(m=>m.id!==r.dataset.id);r.remove()}};$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());
render();if(!me())showLogin();
